require("hop").setup({ keys = "fjdkslawueiromv" })
local hop = require("hop")

vim.keymap.set("", "<leader>hw", function()
	hop.hint_words()
end, { remap = true })
vim.keymap.set("", "<leader>hl", function()
	hop.hint_lines({ multi_windows = true })
end, { remap = true })
vim.keymap.set("", "<leader>hc", function()
	hop.hint_char2()
end, { remap = true })
