require("core.plugin_config.colorscheme")
require("core.plugin_config.lualine")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.treesitter")
require("core.plugin_config.telescope")
require("core.plugin_config.vim-test")
require("core.plugin_config.lsp_config")
require("core.plugin_config.gitsigns")
require("core.plugin_config.hop")
require("core.plugin_config.nvim-cmp")
require("core.plugin_config.whichkey")
require("core.plugin_config.diffview")

